### DISCUSSION TITLE
libnvrtc.so Could not load library libcudnn_cnn_infer.so.8. Error, when use docker image ghcr.io/coqui-ai/tts

### DISCUSSION THREAD

**Discussion by pivolan** [coqui-ai/TTS#2440] [General Q&A]
tried to start first tutorial from you documentation, with your docker image ghcr.io/coqui-ai/tts, to prevent any errors with dependencies, but something gone wrong.
nvidia-smi in docker container available and works well
```
 nvidia-smi
Tue Mar 21 14:08:54 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  Off |
|  0%   60C    P2    80W / 450W |   1525MiB / 24564MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

also code in python show that cuda is available:

```
python3
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```

used this instruction:
https://tts.readthedocs.io/en/latest/training_a_model.html#multi-speaker-training

**Comment by greycubesgav** [comment]
I hit the same problem.
I believe it is related to a PyTorch issue, see https://discuss.pytorch.org/t/could-not-load-library-libcudnn-cnn-infer-so-8/175139/2, which is tracked upstream in the pytorch github repo here: https://github.com/pytorch/pytorch/issues/97041 

One temporary solution is to roll back to a previous release of coqui-ai.tts, for example v0.11.1 seems to work ok.

Example runs as of 2023-03-29:  

**ghcr.io/coqui-ai/tts:latest or ghcr.io/coqui-ai/tts:v0.12.0**
```
$ docker run --rm --gpus all -v ~/tts-output:/root/tts-output ghcr.io/coqui-ai/tts:latest --text "Hello." --out_path /root/tts-output/hello.wav --use_cuda true
 > Downloading model to /root/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC
100%|██████████| 113M/113M [00:02<00:00, 38.1MiB/s]
 > Model's license - apache 2.0
 > Check https://choosealicense.com/licenses/apache-2.0/ for more info.
 > Downloading model to /root/.local/share/tts/vocoder_models--en--ljspeech--hifigan_v2
100%|██████████| 3.80M/3.80M [00:00<00:00, 13.0MiB/s]
Could not load library libcudnn_cnn_infer.so.8. Error: libnvrtc.so: cannot open shared object file: No such file or directory`
```

**ghcr.io/coqui-ai/tts:v0.11.1**
```
docker run --rm --gpus all -v ~/tts-output:/root/tts-output ghcr.io/coqui-ai/tts:v0.11.1 --text "Hello." --out_path /root/tts-output/hello.wav --use_cuda true
 > Downloading model to /root/.local/share/tts/tts_models--en--ljspeech--tacotron2-DDC
100%|██████████| 113M/113M [00:01<00:00, 84.9MiB/s]
 > Model's license - apache 2.0
 > Check https://choosealicense.com/licenses/apache-2.0/ for more info.
 > Downloading model to /root/.local/share/tts/vocoder_models--en--ljspeech--hifigan_v2
100%|██████████| 3.80M/3.80M [00:00<00:00, 25.7MiB/s]
 > Model's license - apache 2.0
 > Check https://choosealicense.com/licenses/apache-2.0/ for more info.
 > Using model: Tacotron2
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Model's reduction rate `r` is set to: 1
 > Vocoder Model: hifigan
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:False
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > pitch_fmin:1.0
 | > pitch_fmax:640.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:2.718281828459045
 | > hop_length:256
 | > win_length:1024
 > Generator Model: hifigan_generator
 > Discriminator Model: hifigan_discriminator
Removing weight norm...
 > Text: Hello.
 > Text splitted to sentences.
['Hello.']
 > Processing time: 0.5840497016906738
 > Real-time factor: 0.564837540450849
 > Saving output to /root/tts-output/hello.wav
```

**Comment by c-ram** [comment]
My workflow is also WSL2 + Docker based. 
(As of 2023-04-01) - Unfortunately, rebuilding the older v0.11.1 image did not seem to help. I imagine it's because they're all dependent on the same nvidia base image.  The fix mentioned in the [link](https://discuss.pytorch.org/t/could-not-load-library-libcudnn-cnn-infer-so-8/175139/2) above helped. 

Specifically, executing this fixed the issue:
`/usr/local/lib/python3.10/dist-packages/torch/lib# ln -s libnvrtc-672ee683.so.11.2 libnvrtc.so`
