### DISCUSSION TITLE
Hangs on dist init process group in distribute py

### DISCUSSION THREAD

**Discussion by JRMeyer** [coqui-ai/TTS#85] [Archived]
<USER>>>> alchemi5t<br/> <DATE> [September 5, 2019, 7:16am]<br/> <br/> I've been trying to use multiple gpus for training but the training<br/> hangs(Responsive, but indefinitely stays here without aby output or<br/> error) at initializing process group. Any insights on how to fix this?<br/> <br/> Tried pytorch 0.4.1 and 1+.<br/> <br/> 'distributed':{<br/> 'backend': 'nccl',<br/> 'url': 'tcp: *slash* / *slash* /localhost:23456'<br/> },<br/> <br/> [This is an archived TTS discussion thread from discourse.mozilla.org/t/hangs-on-dist-init-process-group-in-distribute-py]<br/>

**Comment by JRMeyer** [comment]
<USER>>>> erogol<br/> <DATE> [September 5, 2019, 10:50am]<br/> <br/> I don't have something to replicate your problem hence hard to guess.<br/> But it might be about something your machine's setup, or pytorch version<br/> or dataloader etc.<br/> <br/> [Archived Post]<br/>

**Comment by JRMeyer** [comment]
<USER>>>> alchemi5t<br/> <DATE> [September 19, 2019, 4:54pm]<br/> <br/> Fixed it by installing apex. Not sure why i needed it though.<br/> <br/> [Archived Post]<br/>
