### ISSUE TITLE
[Bug] RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by Coastchb** [coqui-ai/TTS#4010]
### Describe the bug

Hi, all.
I try to train VITS model from scratch with my own data (107 short audios, max duration is 11.87s) or with VCTK dataset and it works.

If I train from scratch with mixed dataset (mix VCTK with my own data), it fails after 600 steps (batchsize=32), with the logs below.

If I finetune the model (trained with VCTK dataset) with F001 dataset,  it fails at the first step.

I want to get a VITS model which can generate voice with the speaker in my own data.

Could you please help me ?
Many thanks!

### To Reproduce

python TTS/bin/train_tts.py --config_path logs/finetune_vits_with_f001_on_vctk/config.json --restore_path logs/train_vits_on_vctk/-October-06-2024_11+52PM-0000000/best_model.pth

### Logs

```shell
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [40,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [40,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
 ! Run is kept in ./logs/finetune_vits_with_f001_on_vctk/-October-07-2024_09+29PM-0000000
Traceback (most recent call last):
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/trainer/trainer.py", line 1833, in fit
    self._fit()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/trainer/trainer.py", line 1785, in _fit
    self.train_epoch()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/trainer/trainer.py", line 1504, in train_epoch
    outputs, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/trainer/trainer.py", line 1383, in train_step
    outputs, loss_dict_new, step_time = self.optimize(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/trainer/trainer.py", line 1226, in optimize
    outputs, loss_dict = self._compute_loss(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/trainer/trainer.py", line 1155, in _compute_loss
    outputs, loss_dict = self._model_train_step(batch, model, criterion, optimizer_idx=optimizer_idx)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/trainer/trainer.py", line 1116, in _model_train_step
    return model.train_step(*input_args)
  File "/workspace/user_code/coastcao/TTS-dev/TTS/tts/models/vits.py", line 1258, in train_step
    outputs = self.forward(
  File "/workspace/user_code/coastcao/TTS-dev/TTS/tts/models/vits.py", line 1021, in forward
    x, m_p, logs_p, x_mask = self.text_encoder(x, x_lengths, lang_emb=lang_emb)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/coastcao/TTS-dev/TTS/tts/layers/vits/networks.py", line 96, in forward
    x = self.encoder(x * x_mask, x_mask)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/coastcao/TTS-dev/TTS/tts/layers/glow_tts/transformer.py", line 420, in forward
    y = self.attn_layers[i](x, x, attn_mask)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/user_code/coastcao/TTS-dev/TTS/tts/layers/glow_tts/transformer.py", line 116, in forward
    q = self.conv_q(x)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

### Environment

```shell
-TTS version: master
-GPU version: P40
-CUDA version: 12.1
-PyTorch version: 2.1.2+cu121
-Python version: 3.10.6
```

**Comment by Coastchb** [comment]
Finally, the problem is solved!

I made two modifications:
1. The speaker idx in speakers_ids.json is not continous: in VCTK the speaker ids ranges from 0 ~ 108, and I added my speaker as 110. I change it to 109, and it works!  I think this mistake is fatal.
2. There are "." "?" ... terminator characters in within transcriptions, as a result the sentence will be split into parts. So I replace these characters with ",".
